### ISSUE TITLE
initial hours more than a day don't show

### ISSUE THREAD

**Issue by receta-erp** [envynoiz/countimer#1]
Starting a new countimer with options set as:
$('#clock').countimer({autoStart : false,leadingZeros: 2,initHours : 139,initMinutes : 03,initSeconds: 34}) 

The initial display shows the hours of 139 as only 19 (ie. it's excluding the fact that 139 includes 5 days (24hrs * 5)

**Comment by PenguinArts** [comment]
+1

**Comment by envynoiz** [comment]
I've added a new version that fix this issue, please feel free to open again if it is necessary.
